/******************************************************************************
* (c) 2019 Copyright, Real-Time Innovations, Inc. All rights reserved.
* No duplications, whole or partial, manual or electronic, may be made
* without express written permission.  Any such copies, or revisions thereof,
* must display this notice unaltered.
* This code contains trade secrets of Real-Time Innovations, Inc.
******************************************************************************/
struct HelloWorld {
    char a;
};
