/*
 * (c) 2018 Copyright, Real-Time Innovations, Inc.  All rights reserved.
 *
 * RTI grants Licensee a license to use, modify, compile, and create derivative
 * works of the Software.  Licensee has the right to distribute object form
 * only for use with RTI products.  The Software is provided "as is", with no
 * warranty of any type, including any warranty for fitness for any purpose.
 * RTI is under no obligation to maintain or support the Software.  RTI shall
 * not be liable for any incidental or consequential damages arising out of the
 * use or inability to use the software.
 */
const long SENSOR_DATA_ARRAY_LENGTH = 4;

@nested
struct SensorAttributes {
    uint32 id;
    float value;
    boolean is_active;
};
 
struct SensorAttributesCollection {
    SensorAttributes sensor_array[SENSOR_DATA_ARRAY_LENGTH];
};

struct SensorData {
    uint32 id[SENSOR_DATA_ARRAY_LENGTH];
    float value[SENSOR_DATA_ARRAY_LENGTH];
    boolean is_active[SENSOR_DATA_ARRAY_LENGTH];
};