/*******************************************************************************
 (c) 2005-2014 Copyright, Real-Time Innovations, Inc.  All rights reserved.
 RTI grants Licensee a license to use, modify, compile, and create derivative
 works of the Software.  Licensee has the right to distribute object form only
 for use with RTI products.  The Software is provided "as is", with no warranty
 of any type, including any warranty for fitness for any purpose. RTI is under
 no obligation to maintain or support the Software.  RTI shall not be liable for
 any incidental or consequential damages arising out of the use or inability to
 use the software.
 ******************************************************************************/
/* hello_world_subscriber.cxx

   A subscription example

   This file is derived from code automatically generated by the rtiddsgen 
   command:

   rtiddsgen -language C++ -example <arch> hello_world.idl

   Example subscription of type hello_world automatically generated by 
   'rtiddsgen'. To test them follow these steps:

   (1) Compile this file and the example publication.

   (2) Start the subscription with the command
       objs/<arch>/hello_world_subscriber <domain_id> <sample_count>

   (3) Start the publication with the command
       objs/<arch>/hello_world_publisher <domain_id> <sample_count>

   (4) [Optional] Specify the list of discovery initial peers and 
       multicast receive addresses via an environment variable or a file 
       (in the current working directory) called NDDS_DISCOVERY_PEERS. 
       
   You can run any number of publishers and subscribers programs, and can 
   add and remove them dynamically from the domain.
              
                                   
   Example:
        
       To run the example application on domain <domain_id>:
                          
       On Unix: 
       
       objs/<arch>/hello_world_publisher <domain_id> 
       objs/<arch>/hello_world_subscriber <domain_id> 
                            
       On Windows:
       
       objs\<arch>\hello_world_publisher <domain_id>  
       objs\<arch>\hello_world_subscriber <domain_id>   
              
       
modification history
------------ -------       
*/

#include <stdio.h>
#include <stdlib.h>
#ifdef RTI_VX653
#include <vThreadsData.h>
#endif
#include "hello_world.h"
#include "hello_worldSupport.h"
#include "ndds/ndds_cpp.h"

/******************************************************************************
  Macros to read input parameters
******************************************************************************/

#define READ_INTEGER_PARAM(parameter,outValue)\
    if (!strcmp(argv[i],parameter)) {\
        if (i+1 >= argc) {\
            printf("%s",syntax);\
            return 1;\
        }\
        i++;\
        outValue = atoi(argv[i]);\
        i++;\
        continue;\
    }        

#define READ_STRING_PARAM(parameter,outValue)\
    if (!strcmp(argv[i],parameter)) {\
        if (i+1 >= argc) {\
            printf("%s",syntax);\
            return 1;\
        }\
        i++;\
        outValue=argv[i];\
        i++;\
        continue;\
    }       

class hello_worldListener: public DDSDataReaderListener {
public:
    virtual void on_requested_deadline_missed(DDSDataReader* /*reader*/,
            const DDS_RequestedDeadlineMissedStatus& /*status*/) {
    }

    virtual void on_requested_incompatible_qos(DDSDataReader* /*reader*/,
            const DDS_RequestedIncompatibleQosStatus& /*status*/) {
    }

    virtual void on_sample_rejected(DDSDataReader* /*reader*/,
            const DDS_SampleRejectedStatus& /*status*/) {
    }

    virtual void on_liveliness_changed(DDSDataReader* /*reader*/,
            const DDS_LivelinessChangedStatus& /*status*/) {
    }

    virtual void on_sample_lost(DDSDataReader* /*reader*/,
            const DDS_SampleLostStatus& /*status*/) {
    }

    virtual void on_subscription_matched(DDSDataReader* /*reader*/,
            const DDS_SubscriptionMatchedStatus& /*status*/) {
    }

    virtual void on_data_available(DDSDataReader* reader);
};

void hello_worldListener::on_data_available(DDSDataReader* reader) {
    hello_worldDataReader *hello_world_reader = NULL;
    hello_worldSeq data_seq;
    DDS_SampleInfoSeq info_seq;
    DDS_ReturnCode_t retcode;
    int i;

    hello_world_reader = hello_worldDataReader::narrow(reader);
    if (hello_world_reader == NULL) {
        printf("DataReader narrow error\n");
        return;
    }

    retcode = hello_world_reader->take(data_seq, info_seq, DDS_LENGTH_UNLIMITED,
            DDS_ANY_SAMPLE_STATE, DDS_ANY_VIEW_STATE, DDS_ANY_INSTANCE_STATE);

    if (retcode == DDS_RETCODE_NO_DATA) {
        return;
    } else if (retcode != DDS_RETCODE_OK) {
        printf("take error %d\n", retcode);
        return;
    }

    for (i = 0; i < data_seq.length(); ++i) {
        if (info_seq[i].valid_data) {
            hello_worldTypeSupport::print_data(&data_seq[i]);
        }
    }

    retcode = hello_world_reader->return_loan(data_seq, info_seq);
    if (retcode != DDS_RETCODE_OK) {
        printf("return loan error %d\n", retcode);
    }
}

/* Delete all entities */
static int subscriber_shutdown(DDSDomainParticipant *participant) {
    DDS_ReturnCode_t retcode;
    int status = 0;

    if (participant != NULL) {
        retcode = participant->delete_contained_entities();
        if (retcode != DDS_RETCODE_OK) {
            printf("delete_contained_entities error %d\n", retcode);
            status = -1;
        }

        retcode = DDSTheParticipantFactory->delete_participant(participant);
        if (retcode != DDS_RETCODE_OK) {
            printf("delete_participant error %d\n", retcode);
            status = -1;
        }
    }

    /* RTI Connext provides the finalize_instance() method on
       domain participant factory for people who want to release memory used
       by the participant factory. Uncomment the following block of code for
       clean destruction of the singleton. */
/*
    retcode = DDSDomainParticipantFactory::finalize_instance();
    if (retcode != DDS_RETCODE_OK) {
        printf("finalize_instance error %d\n", retcode);
        status = -1;
    }
*/
    return status;
}

extern "C" int subscriber_main(int domain_id, int sample_count, int drs) {
    DDSDomainParticipant *participant = NULL;
    DDSSubscriber *subscriber = NULL;
    DDSTopic *topic = NULL;
    hello_worldListener *reader_listener = NULL;
    DDSDataReader *reader = NULL;
    DDS_ReturnCode_t retcode;
    const char *type_name = NULL;
    int count = 0;
    DDS_Duration_t receive_period = { 4, 0 };
    int status = 0;

    /* To customize the participant QoS, use 
     the configuration file USER_QOS_PROFILES.xml */
    participant = DDSTheParticipantFactory->create_participant(domain_id,
            DDS_PARTICIPANT_QOS_DEFAULT, NULL /* listener */,
            DDS_STATUS_MASK_NONE);
    if (participant == NULL) {
        printf("create_participant error\n");
        subscriber_shutdown(participant);
        return -1;
    }

    /* To customize the subscriber QoS, use 
     the configuration file USER_QOS_PROFILES.xml */
    subscriber = participant->create_subscriber(DDS_SUBSCRIBER_QOS_DEFAULT,
            NULL /* listener */, DDS_STATUS_MASK_NONE);
    if (subscriber == NULL) {
        printf("create_subscriber error\n");
        subscriber_shutdown(participant);
        return -1;
    }

    /* Register the type before creating the topic */
    type_name = hello_worldTypeSupport::get_type_name();
    retcode = hello_worldTypeSupport::register_type(participant, type_name);
    if (retcode != DDS_RETCODE_OK) {
        printf("register_type error %d\n", retcode);
        subscriber_shutdown(participant);
        return -1;
    }

    /* To customize the topic QoS, use 
     the configuration file USER_QOS_PROFILES.xml */
    topic = participant->create_topic("Example hello_world", type_name,
            DDS_TOPIC_QOS_DEFAULT, NULL /* listener */, DDS_STATUS_MASK_NONE);
    if (topic == NULL) {
        printf("create_topic error\n");
        subscriber_shutdown(participant);
        return -1;
    }

    /* Create a data reader listener */
    reader_listener = new hello_worldListener();
    
    /* If you use Durable Reader State, you need to set up several properties.
     * In this example, we have modified them using a QoS XML profile. See
     * further details in USER_QOS_PROFILES.xml.
     */

    if (drs == 1) {
        reader = subscriber->create_datareader_with_profile(topic,
                "persistence_example_Library", "durable_reader_state_Profile",
                reader_listener, DDS_STATUS_MASK_ALL);
        if (reader == NULL) {
            printf("create_datareader error\n");
            subscriber_shutdown(participant);
            delete reader_listener;
            return -1;
        }
    } else {
        reader = subscriber->create_datareader_with_profile(topic,
                "persistence_example_Library", "persistence_service_Profile",
                reader_listener, DDS_STATUS_MASK_ALL);
        if (reader == NULL) {
            printf("create_datareader error\n");
            subscriber_shutdown(participant);
            delete reader_listener;
            return -1;
        }
    }

    /* Main loop */
    for (count = 0; (sample_count == 0) || (count < sample_count); ++count) {

        printf("hello_world subscriber sleeping for %d sec...\n",
                receive_period.sec);

        NDDSUtility::sleep(receive_period);
    }

    /* Delete all entities */
    status = subscriber_shutdown(participant);
    delete reader_listener;

    return status;
}

int main(int argc, char *argv[]) {
    int domain_id = 0;
    int sample_count = 0; /* infinite loop */
    int drs = 0;
    int i;
    char syntax[1024];

    sprintf(syntax,
            "%s [options] \n\
    -domain_id <domain ID> (default: 0)\n\
    -sample_count <sample_count> (default: infinite => 0) \n\
    -drs <1|0> Enable/Disable durable reader state (default: 0)\n",
            argv[0]);

    for (i = 1; i < argc;) {
        READ_INTEGER_PARAM("-sample_count", sample_count);
        READ_INTEGER_PARAM("-domain_id", domain_id);
        READ_INTEGER_PARAM("-drs", drs);
        printf("%s", syntax);
        return 0;
    }


    /* Uncomment this to turn on additional logging
    NDDSConfigLogger::get_instance()->
        set_verbosity_by_category(NDDS_CONFIG_LOG_CATEGORY_API, 
                                  NDDS_CONFIG_LOG_VERBOSITY_STATUS_ALL);
    */

    return subscriber_main(domain_id, sample_count, drs);
}


#ifdef RTI_VX653
const unsigned char* __ctype = *(__ctypePtrGet());

extern "C" void usrAppInit ()
{
#ifdef  USER_APPL_INIT
    USER_APPL_INIT; /* for backwards compatibility */
#endif

    /* add application specific code here */
    taskSpawn("sub", RTI_OSAPI_THREAD_PRIORITY_NORMAL, 0x8, 0x150000,
            (FUNCPTR)subscriber_main, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

}
#endif

